image:
  name: alpine/helm:3.5.4
  entrypoint: ["/bin/sh", "-c"]

lint:
  stage: test
  script:
    - helm lint

pages:
  stage: deploy
  script:
    - mkdir public
    - helm package .
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME} .
    - mv index.yaml django-*.tgz ./public
  artifacts:
    paths:
      - public
  only:
    - master
    - tags
